# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: M's Lab. （えむらぼ）
email: nmukai@sugiyama-u.ac.jp
description: 椙山女学園大学 文化情報学部 向研究室のブログです。授業資料など技術的な情報の他、女子大教員の日常を４コマ漫画形式で公開しています。
baseurl: ""
url: "http://mukai-lab.info/"
github_username:  naoto-github
facebook_username: nmukai1978
twitter_username: nmukai1978

# Build settings
markdown: kramdown
#markdown: redcarpet

#highlight
highlighter: rouge
#highlighter: pygments

kramdown:
    input: GFM
    syntax_highlighter: rouge

#除外ファイル
exclude: ["img", "Gemfile", "Gemfile.lock"]

#タイムゾーン
timezone: Japan

#対象ファイル・フォルダの追加
include: ["class/programming_1/","class/applied_programming/"]

#プラグイン
gems: ["jekyll-gist", "jekyll-paginate"]
gist:
    noscript: false

#ページネーション
paginate: 5
